version: 2

references:
  container_config: &container_config
    docker:
      # Main Python container
      - image: circleci/python:3.6.2
        environment:
          TAP_POSTGRES_PORT: 5432
          TAP_POSTGRES_USER: test_user
          TAP_POSTGRES_PASSWORD: my-secret-passwd
          TAP_POSTGRES_HOST: test_postgres

      # PostgreSQL service container image used as test source database
      - image: postgres:11.4
        name: test_postgres
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: my-secret-passwd
          POSTGRES_DB: tap_postgres_test
        ports:
          - 5432:5432

jobs:
  build:
    <<: *container_config

    steps:
      - checkout
      - run:
          name: 'Setup virtual environment'
          command: |
            python3 -m venv ./virtualenvs/tap-postgres
            . ./virtualenvs/tap-postgres/bin/activate
            pip install --upgrade pip setuptools
            pip install -e .[test]

      - run:
          name: Check dependencies for conflict
          command: |
            . ./virtualenvs/tap-postgres/bin/activate
            pip check && echo "No conflicts" || exit 1

      - run:
          name: 'Pylinting'
          command: |
            . ./virtualenvs/tap-postgres/bin/activate
            make pylint

      - run:
          name: 'Tests'
          command: |
            . ./virtualenvs/tap-postgres/bin/activate
            export LOGGING_CONF_FILE=./sample_logging.conf
            make test

workflows:
  version: 2
  build:
    jobs:
      - build
